# Generated by Django 4.0 on 2023-07-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0005_rename_image_blogpostmodel_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
