# Generated by Django 4.0 on 2023-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_blogpostmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='blog.Category'),
        ),
    ]
