# Generated by Django 4.0 on 2023-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpostmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='category',
            field=models.ManyToManyField(related_name='catitems', to='blog.Category'),
        ),
    ]
