# Generated by Django 4.0 on 2023-07-31 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0010_alter_blogpostmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
